config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'posts#index'

  resources :posts, only: [:new, :create, :show] do
    resources :comments, only: [:new, :create, :destroy]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :post

  validates :body, :post_id, :user_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :body, :title, :user_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
	  @post = Post.find(params[:post_id])
      @comment = @post.comments.create!(comment_params.merge(user_id: current_user.id))
      # current_user.comments << @comment
      redirect_to post_path(@post)
	end

	def destroy 
	  @comment = Comment.find(params[:id])
	  @comment.destroy!
	  redirect_to post_path(params[:post_id])
	end


    private

	def comment_params
      params.require(:comment).permit(:body)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order(created_at: :desc).page(params[:page])
  end

  def create
    @post = Post.create!(post_params.merge(user_id: current_user.id))
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.order(created_at: :desc).page(params[:page])
  end

  private

  def post_params
    params.require(:post).permit(:body, :title)
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    root_url
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_in_path_for(resource)
    root_url
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def comment_belongs_to_current_user?(comment)
      comment.user == current_user 
    end

   # these three methods are used for devise form modals
    def resource
      @resource ||= User.new
    end

    def resource_name
      :user
    end

    def devise_mapping
     @devise_mapping ||= Devise.mappings[:user]
    end
end

app/views/comments/_comment.html.erb
<div class="well">	
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title"><%=  comment.user.email %></h3>
	  </div>
	  <div class="panel-body">
	    <%= comment.body %>
	  </div>
	  <% if comment_belongs_to_current_user?(comment) %>
	  	<div class="panel-footer">
	  		<%= link_to 'Delete Comment', post_comment_path(comment.post, comment), method: :delete, class: 'btn btn-block btn-danger' %>
	  	</div>
	  <% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessagingBoardApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default">
  <div class="container-fluid">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to 'Home', root_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><% if user_signed_in? %>
        	  <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
        	  <% else %>
        	    <%= link_to 'Log In', '#signinModal', data: { toggle: 'modal', target: '#signinModal'} %>
        	    <% end %>
        </li>
        <li><%= link_to 'Sign Up', '#signupModal', data: { toggle: 'modal', target: '#signupModal' } %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%= render partial: 'devise/registrations/signup' %>

<%= yield %>

<%= render partial: 'devise/registrations/signin' %>


</body>
</html>

app/views/posts/_addpost.html.erb
<div class="modal fade" id="addPostModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Create a Post</h4>
        </div>
        <div class="modal-body">
          <%= bootstrap_form_for :post, url: posts_path do |f| %>
               <%= f.text_area :body, required: true %>
               <%= f.text_field :title, required: true %>
               <%= f.submit %>
            <% end %>

        </div>
      </div>
    </div>
</div

app/views/posts/_post.html.erb
<div class="text-center">
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title"><%= link_to post.title, post_path(post) %></h3>
	  </div>
	  <div class="panel-body">
	    <%= post.body %>
	  </div>
	  <div class="panel-footer">
	  	<div class="dropdown">
		  	<% if user_signed_in? %>
		  	   <button class="btn btn-default btn-block" id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Leave a Comment
		  	   	  <span class="caret"></span>
		  	  </button>	
		  	  <ul class="dropdown-menu col-md-10" aria-labelledby="dLabel" id="comment-dropdown-menu">
		  	  	<div class="text-center">
	                <%= bootstrap_form_for :comment , url: post_comments_path(post) do |f| %>
		  	           <%= f.text_area :body, required: true %>
		  	           <%= f.submit %>
		  	        <% end %>
	  	       </div>
              </ul>
		  	<% else %>
		  	    <a class='btn btn-default disabled' id="comment-button">Must be logged in to comment</a>
		  	<% end %>
	  </div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-3">
		</div>
	    	<div class="col-md-6">
	    		<div class="row">
	    			<% if user_signed_in? %>
	    		  		<a class="btn btn-default btn-block" data-toggle="modal" data-target="#addPostModal" id="add-post"> Add a New Post</a>
	    		  	<% else %>
						<a class="btn btn-default btn-block disabled" id="add-post"> Must be logged in to Post</a>
	    		  	<% end %> 
	    		</div>
	    	    </br>
	    	</br>

	    		<div class="row">
	    	    	<%= render partial: 'addpost' %>
	    	    </div>
	    	    <div class="row">
	    	    	<%= paginate @posts %>
                	<%= render partial: 'post', collection: @posts %>
				</div>
	    	</div>
    </div>
</div>

app/views/posts/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-3">
	    </div>
	    	<div class="col-md-6" data-send-comment="true">
	    		<%= paginate @comments %>
				<%= render partial: 'post', locals: { post: @post } %>
				<%= render partial: 'comments/comment', collection: @comments %>
			</div>
	</div>
</div>